# Generated by Django 5.2.1 on 2025-06-25 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntryJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Write about your day, how are you feeling or anything in your mind ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moods', models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('anxious', '😟 Anxious'), ('stressed', '😫 Stressed'), ('calm', '😌 Calm'), ('excited', '😃 Excited'), ('neutral', '😐 Neutral')], help_text='How are you feeling? ', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
