# Generated by Django 5.2.1 on 2025-06-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentryjournal',
            old_name='moods',
            new_name='mood',
        ),
    ]
