# Generated by Django 5.2.1 on 2025-06-29 05:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_rename_moods_userentryjournal_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentryjournal',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
